CREATE TABLE IF NOT EXISTS players (xuid TEXT PRIMARY KEY, key TEXT NOT NULL, name TEXT, created INTEGER, last_seen INTEGER, alt TEXT);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, xuid TEXT NOT NULL, created INTEGER);
CREATE TABLE IF NOT EXISTS teams (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE COLLATE NOCASE, owner TEXT NOT NULL, created INTEGER, profile TEXT, wins INTEGER DEFAULT 0, losses INTEGER DEFAULT 0, cash INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS members (team_id INTEGER NOT NULL, xuid TEXT NOT NULL, role INTEGER NOT NULL, joined INTEGER, PRIMARY KEY (team_id, xuid));
CREATE TABLE IF NOT EXISTS invites (team_id INTEGER NOT NULL, xuid TEXT NOT NULL, from_xuid TEXT, created INTEGER, PRIMARY KEY (team_id, xuid));
CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, to_xuid TEXT NOT NULL, type INTEGER NOT NULL, from_xuid TEXT, from_name TEXT, team_id INTEGER, team_name TEXT, created INTEGER);
CREATE TABLE IF NOT EXISTS stats (entity TEXT NOT NULL, board INTEGER NOT NULL, data TEXT, updated INTEGER, PRIMARY KEY (entity, board));
CREATE TABLE IF NOT EXISTS log (id INTEGER PRIMARY KEY AUTOINCREMENT, at INTEGER, xuid TEXT, what TEXT);
